In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.3.1+cpu


In [2]:
#Tensors: 3D Matrix. Way to represent data. The core of deep learning
#and neural networks

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
#Scalar has 0 dimensions. It is a single number


0

In [5]:
#Get tensor as Python int
scalar.item()

7

In [6]:
#Vector. 1 dimensional array
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix. 2 Dimension array
Matrix = torch.tensor([[7,8],
                       [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
print(Matrix[0])
Matrix[1]

tensor([7, 8])


tensor([ 9, 10])

In [12]:
#Tensor. Multi Dimension Array
Tensor = torch.tensor([[[1,2],[3,4]],
                       [[5,6],[7,8]
                       ],[[1,2],[3,4]],
                       [[5,6],[7,8]
                       ]])

Tensor

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [13]:
Tensor.ndim

3

In [14]:
Tensor.shape

torch.Size([4, 2, 2])

In [15]:
# Random Tensors
# Random tensors becuase the way neural networks learn is that
# they start with tensors full of random numbers and then adjust those
# random numbers to better represent the data.

# Start with random number -> look at data -> update random numbers -> look at data -> update random tensor

In [16]:
# Create a random tensor of size data

random_tensor = torch.rand(6,3,3)

random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(6,3,3)) # height width, color channel (R,G,B)

random_image_size_tensor

tensor([[[0.8145, 0.8311, 0.4427],
         [0.4386, 0.7331, 0.5269],
         [0.9063, 0.1186, 0.3368]],

        [[0.4878, 0.9742, 0.2218],
         [0.2831, 0.0557, 0.9205],
         [0.8375, 0.1553, 0.9091]],

        [[0.6988, 0.5629, 0.5425],
         [0.0141, 0.5536, 0.4923],
         [0.8304, 0.9586, 0.4439]],

        [[0.2433, 0.9873, 0.2749],
         [0.1651, 0.1984, 0.8613],
         [0.9370, 0.0889, 0.4873]],

        [[0.5906, 0.5147, 0.0749],
         [0.3291, 0.9570, 0.3628],
         [0.5302, 0.5900, 0.4258]],

        [[0.7254, 0.6272, 0.5452],
         [0.4920, 0.5879, 0.3365],
         [0.1946, 0.0172, 0.2171]]])

In [18]:
# Tensor of all zeroes

zeros = torch.zeros(size=(3,3,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [19]:
# Tensor of all ones

ones = torch.ones(size=(3,3,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [20]:
torch.arange(start=1, end=1000, step=69)

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [21]:
#Tensors like
one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Tensor Data Types
#Tensor datatype is one of the 3 biggest errors you'll run into with PyTorch

float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, #What is the tensor datatype?
                               device="cpu", #Tensor on CPU or GPU?
                               requires_grad=False) #Tensor operations tracks gradients

In [23]:
np1 = np.random.rand(3,4)
np1

array([[0.64334096, 0.81962658, 0.33558057, 0.5794806 ],
       [0.59750933, 0.94559822, 0.75083069, 0.35392751],
       [0.32745714, 0.28991164, 0.39959188, 0.8282254 ]])

In [24]:
np1.dtype

dtype('float64')

In [25]:
tensor = torch.tensor(np1, dtype=torch.float32)
tensor

tensor([[0.6433, 0.8196, 0.3356, 0.5795],
        [0.5975, 0.9456, 0.7508, 0.3539],
        [0.3275, 0.2899, 0.3996, 0.8282]])

In [26]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Reshape and View
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
#Reshape if we don't know number of items. Use -1 if number in x is disivible by total no. of elements in Tensor
my_torch2 = torch.arange(10)

my_torch2.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
#When you make a change to a Tensor, any Tensor that has operations using the changed 
#Tensor will have it's values updated accordingly.

In [30]:
my_torch3 = my_torch2.reshape(5,2)
print(my_torch3)
print(my_torch3[3])
print(my_torch3[:,1])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([6, 7])
tensor([1, 3, 5, 7, 9])


In [31]:
my_torch4 = my_torch2.reshape(2,5)

In [32]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])